### ISSUE TITLE
Changing "authorization_required" key in configmap fails deployment in OpenShift

### ISSUE THREAD

**Issue by shukapoo** [elixir-europe/WES-ELIXIR#138]
**Describe the bug**
Changes in configmap for authorization_required key fails the WES deployment in OpenShift

**To Reproduce**
Setting  authorization_required: True in configmap fails the deployment
**Expected behavior**

**Screenshots**

[2020-03-10 07:33:49,846: INFO    ] Celery task monitor registered. [wes_elixir.tasks.register_celery]
--
  | [2020-03-10 07:33:49 +0000] [11] [ERROR] Exception in worker process
  | Traceback (most recent call last):
  | File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
  | worker.init_process()
  | File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
  | self.load_wsgi()
  | File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
  | self.wsgi = self.app.wsgi()
  | File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
  | self.callable = self.load()
  | File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
  | return self.load_wsgiapp()
  | File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
  | return util.import_app(self.app_uri)
  | File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
  | __import__(module)
  | File "/app/wes_elixir/wsgi.py", line 3, in <module>
  | app, config = run_server()
  | File "/app/wes_elixir/app.py", line 41, in run_server
  | 'authorization_required'
  | File "/app/wes_elixir/api/register_openapi.py", line 39, in register_openapi
  | path = __add_security_definitions(in_file=path)
  | File "/app/wes_elixir/api/register_openapi.py", line 90, in __add_security_definitions
  | copyfile(in_file, out_file)
  | File "/usr/local/lib/python3.6/shutil.py", line 121, in copyfile
  | with open(dst, 'wb') as fdst:
  | PermissionError: [Errno 13] Permission denied: '/app/wes_elixir/api/20181010.be85140.workflow_execution_service.swagger.modified.yaml'

**Comment by uniqueg** [comment]
Resolved by #148
