### ISSUE TITLE
Migrate boilerplate to FOCA v0.10.0

### ISSUE THREAD

**Issue by uniqueg** [elixir-europe/WES-ELIXIR#153]
A lot of the code shared between this service and others in the organizationhas been moved to the [FOCA](https://github.com/elixir-cloud-aai/foca) archetype.

Duplicate code should be removed from this service and, where necessary, the remaining code should be refactored to make use of FOCA.

**Comment by uniqueg** [comment]
@sarthak-sopho: for your interest

**Comment by sarthakgupta072** [comment]
Sure Alex :)

**Comment by uniqueg** [comment]
Great - note that if you do that, you can copy this meta issue to proTES, proWES etc as well (see issue description for full list). It's probably better to change one module at a time in all services that use that module rather than changing all modules in one service in one go.

**Comment by sarthakgupta072** [comment]
Yeah, I'll change one module at a time.

**Comment by uniqueg** [comment]
Guess at this point it makes sense to replace everythin at once :)

**Comment by kushagra189** [comment]
Picking this up on priority as this is a blocker for our current hackathon milestones.
