### ISSUE TITLE
Some inconsistencies in the documentation

### ISSUE THREAD

**Issue by sgalpha01** [elixir-europe/WES-ELIXIR#237]
**Describe the bug**
Technically it's not a bug with programs, but there are some issues in the doc.

**Issues**

1. cloning the repo in the directory name `app`
2. the grep command looks for `cwl-wes_wes-worker`, but due to issue (1), it's not present
3. Wrong port is used in the example as it does not match with `docker-compose` file

**Expected documentation**

1. the repo can be downloaded as it is.
2. grep should look for `_wes-worker` instead of `cwl-wes_wes-worker`
3. Port should be updated to `8080`

**Comment by sgalpha01** [comment]
Should I go ahead and edit the Readme file?

**Comment by uniqueg** [comment]
Yes, please - if it's not too late. Sorry, I'm just getting around going through all my GH notifications.
