### ISSUE TITLE
Implement CI/CD workflow

### ISSUE THREAD

**Issue by fgypas** [elixir-europe/WES-ELIXIR#38]
**Is your feature request related to a problem? Please describe.**
Add Travis Continuous Integration.

**Describe the solution you'd like**
Travis CI that runs in every pull request on the dev or master branch. It sould use docker and docker-compose.

**Comment by fgypas** [comment]
For CD maybe Jenkins is better.

**Comment by MariusDieckmann** [comment]
Implemented branch dependend building of the docker images based on branches using travis.

**Comment by uniqueg** [comment]
A first reasonably solid CI workflow with Travis CI is finally implemented (#125). New issues will be added to support changes to the `master` branch / version tags and CD.
