### ISSUE TITLE
WES client for testing, CLI and Swagger-independent UI use

### ISSUE THREAD

**Issue by uniqueg** [elixir-europe/WES-ELIXIR#51]
**Is your feature request related to a problem? Please describe.**
While Swagger UI is great for demo and API documentation/exploration purposes, it is not fit for use in testing or production. Moreover, Swagger 2.0 does not support multiple file uploads and thus cannot be used to properly handle the `workflow_attachment` field in requests to the `POST /runs` endpoint.

**Describe the solution you'd like**
Develop a CLI client that can be used for testing and in production, e.g., by running it in a user-facing web service. The client should validate WES requests and responses according to specs and support the OAuth2 implicit flow authorization scheme. In Python this could be done e.g. with Yelp's [bravado](https://github.com/Yelp/bravado) and [bravado-core](https://github.com/Yelp/bravado), given the WES specs (current commit: [be85140](https://github.com/ga4gh/workflow-execution-service-schemas/blob/be851403aa845f2be1661671f0021dd76ebbabd1/openapi/workflow_execution_service.swagger.yaml)).

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by fgypas** [comment]
We are implementing a WES client in a different repo:
https://github.com/zavolanlab/WES-cli

**Comment by fgypas** [comment]
Forked here: https://github.com/elixir-europe/WES-cli

**Comment by fgypas** [comment]
We have a simple client that works without authentication.
