### ISSUE TITLE
Add nginx with ssl support

### ISSUE THREAD

**Issue by fgypas** [elixir-europe/WES-ELIXIR#75]
**Is your feature request related to a problem? Please describe.**
Nginx with SSL support to use for production deployment. Required also for testing the bravado client.

**Describe the solution you'd like**
Add Nginx config and update docker-compose files.

**Describe alternatives you've considered**
Alternatively, we could use apache.

**Comment by fgypas** [comment]
I am working on it on the branch nginx_with_ssl_support https://github.com/elixir-europe/WES-ELIXIR/tree/nginx_with_ssl_support

**Comment by MariusDieckmann** [comment]
Maybe not required since TLS is provided by Kubernetes?

**Comment by fgypas** [comment]
I agree. The only reason I don't close the issue yet because I am testing SSL for the WES-cli and nginx is the easiest way to have ssl.

**Comment by fgypas** [comment]
Closing for now
