### ISSUE TITLE
Production grade Flask deployment

### ISSUE THREAD

**Issue by djixyacine** [elixir-europe/WES-ELIXIR#80]
**Is your feature request related to a problem? Please describe.**
The current Flask application is not production grade, and should be used for development environments only.

**Describe the solution you'd like**
* A proper Gunicorn app on top of Flask would be a better option for a production grade deployment.
* Moreover, FTP credentials should be handled via environment variables. That is not only more secure, but it also makes the application very flexible in terms of OpenShift/Kubernetes deployments.

**Comment by uniqueg** [comment]
I think this is more or less handled.
