### ISSUE TITLE
New cwltool version incompatible with cwl-tes

### ISSUE THREAD

**Issue by aniewielska** [elixir-europe/WES-ELIXIR#99]
cwl-tes in the dev version currently pulls the newest version of cwltool and that version is incompatible with cwl-tes. You know about it already, so I will omit the steps, how to reproduce that etc.

There is additional requirement for the shared storage solution, that cwltool needs to be in such a version, that creates temporary directories relative to cwl-tes execution directory and not relative to global tmp directory. 
So if we set 
```
storage.tmp_dir: '/data/tmp'
```
in WES-ELIXIR
we expect cwl-tes to produce temporary directories in `/data/tmp` and not in `/tmp`
We know, that it works as expected for cwltool version:

`cwltool==1.0.20181217162649`

and does not work as expected for the version

`cwltool==1.0.20181201184214`

Integrated WES-TES solution, would be to fix cwltool version to `1.0.20181217162649`
This version should work for FTP as well and is compatible with the current version of cwl-tes.

**Comment by uniqueg** [comment]
Fixed by c4ad2b4da44138732288d4e7ea7135490913e73f
